components/AgreementCard/index.js
components/AgreementCard/styles.js
components/Home/index.js
components/Home/styles.js
data/agreements.js
package-lock.json
package.json

closes #https://github.com/openpolitica/proclama-preliminar/issues/2
mirrors https://github.com/openpolitica/proclama-preliminar/pull/7

Agreements section 2

---

components/Home/index.js
components/SignatureCount/index.js
components/SignatureCount/styles.js
package-lock.json
package.json
pages/api/signatures/index.js
pages/index.js

Se conecta con la petición de https://www.change.org/p/actransparencia-keikofujimori-pedrocastillote-canaln-que-los-candidatos-pedro-castillo-y-keiko-fujimori-firmen-la-siguiente-proclama-ciudadana con la finalidad de obtener el valor de las firmas desde el script cargado en dicha página.
Adiciona el componente de firmas y un ejemplo de inclusión en la página principal.
Considerar que el script de la página de change.org de donde se obtiene el valor de las firmas, scrapeada en `pages/api/signatures/index.js` tiene la siguiente estructura:
```
window.changeTargetingData=
{
reactFe: true,
appState: { utmParams: {}, countryCode: 'PE', locale: 'es-419' },
viewer: { user: {} },
petition: {
id: '28767136',
user: { id: '1150815096', displayName: 'Ivan Lanegra', photo: null },
organization: {
id: …
```

Add dynamic signature 2

---

components/Home/index.js

Actualiza la información de los URLs en change.org y en descargas así como el fraseo del link de descarga.
Closes #10 y #11

Actualiza los URLs de change org y descarga / actualiza fraseo de descarga

---

components/SEO/index.js

Adiciona una "a" faltante al texto de OG.

Corrige sintaxis en texto de descripción de OG

---

components/AgreementCard/styles.js
components/Home/index.js
components/Home/styles.js
components/SignatureCount/index.js
components/SignatureCount/styles.js
data/agreements.js

Actualiza el contenido según la información en https://www.figma.com/file/UDTlFfYsSdDNJDDOf5QsIF/Landing-page?node-id=33%3A79 y en https://drive.google.com/drive/folders/1VOIKXOhmWCaq53jhk6Ygza1izBFxBz7c
Closes #21 
Closes #23

Actualiza el contenido de los acuerdos de la proclama / actualiza texto en firmas

---

components/Home/index.js
components/Home/styles.js

Closes 
https://github.com/openpolitica/proclama-preliminar/issues/25
https://github.com/openpolitica/proclama-preliminar/issues/24

Update style in signatures and fix styles in header and hero section

---

components/Home/index.js
components/Home/styles.js
components/SignatureCount/styles.js

Actualiza tamaño de fuente según diseño en figma: https://www.figma.com/file/UDTlFfYsSdDNJDDOf5QsIF/Landing-page?node-id=110%3A158
closes #27

Actualiza el estilo del texto de la firma para pantallas de móviles

---

models/Agreements.js
models/Events.js
package-lock.json
package.json
pages/api/agreements/index.js
pages/api/events/[id].js
pages/api/events/index.js
util/mongodb.js

Se han agregado los Schemas usados así como los endpoints para cada Schema.
`Agreements`
`Events`
Además se ha modificado la conexión hacia la BD a través de `mongoose`

Creación de Schemas y Endpoints

---

.babelrc
components/Button/index.js
components/Button/styles.js
components/FooterInfo/index.js
components/FooterInfo/styles.js
components/Form/index.js
components/Form/styles.js
components/Login/index.js
components/Login/styles.js
components/TextInput/index.js
components/TextInput/styles.js
lib/fetchJson.js
lib/session.js
package-lock.json
package.json
pages/api/agreements/index.js
pages/api/events/index.js
pages/api/login/index.js
pages/api/logout/index.js
pages/update-form/index.js
pages/update-form/login.js

- Utiliza el contraseña para iniciar sesión.
- Se crea una página de inicio de sesión solamente para ingreso de contraseña. Se verifica si la contraseña es correcta o no y se muestra un mensaje en caso que no lo sea.
- Cuando se ingresa a `update-form/` se redirige automáticamente a `update-form/login` para ingresar los datos.
- Se crea una página de formulario para ingresar los datos correspondientes al evento. Al hacer clic en actualizar, se conecta con la base de datos mediante una llamada a la API y actualiza la información mostrando un mensaje con el prompt y una vista de resumen con la información enviada.  En la vista de resumen se tiene un botón para regresar a la vista de envío de nueva actualización.
- Tanto en la vista de formulario como la vista de resumen se tiene un botón …

Adiciona formulario para actualización de eventos

---

components/Alert/index.js
components/Alert/styles.js
components/EventCard/index.js
components/EventCard/styles.js
components/Home/index.js
package-lock.json
public/images/icons/arrow-right.svg

- Update svg and styles
- Show last events
- Update yes/no/risk styles

Add status agreement and events updates

---

components/Home/index.js

Se cambia los títulos haciendo referencia explícita al Presidente
closes #51

Actualiza los títulos de acuerdo con el estado actual de la elección presidencial

---

components/Alert/styles.js
components/EventCard/index.js
components/EventCard/styles.js
components/Form/index.js
components/Home/index.js

- Agreement title instead of event title
- Change styles for title and description
- Add overflow property to prevent overflow outside the event card
closes #52 
- Change border of eventCard
closes #55

Corrige el título de eventCard / cambia borde de eventCard

---

components/Home/styles.js
global-styles/global.js

Actualiza colores de acuerdo con diseño https://www.figma.com/file/UDTlFfYsSdDNJDDOf5QsIF/Homepage?node-id=307%3A4790 
closes #53

Actualiza color de fondo de la página y del encabezado

---

components/AgreementCard/index.js
components/AgreementCard/styles.js

- Update the backgound, border and gradient
- Change visibility of description in mobile according to design
closes #54

Actualiza color y borde de AgreementCard

---

components/Alert/index.js
components/Alert/styles.js
components/EventCard/styles.js
components/Form/index.js
models/Events.js

Actualiza la información de acuerdo a los niveles de alerta establecidos en:
- Esquema del modelo en backend
- Alternativas en el formulario
- Opciones en el frontend
- Estilos en frontend
Closes #71 , #73

Actualiza los niveles de alerta y las palabras claves 

---

components/EventCard/index.js
components/Form/index.js
components/Home/index.js
components/SEO/index.js
components/SignatureCount/index.js

Reemplaza acuerdos por compromisos en todas las instancias de la aplicación.

Cambiar la palabra "acuerdos" a "compromisos"

---

components/SEO/index.js

Cambia la ruta a vigilantes.pe en lugar de la anterior proclamaciudadana.pe

Change path OG image

---

components/Alert/styles.js

Update according to Figma:
https://www.figma.com/file/UDTlFfYsSdDNJDDOf5QsIF/Homepage?node-id=288%3A2236 
Closes #89

Update colors in alert

---

components/AgreementCard/index.js
components/AgreementCard/styles.js

- Delete alert
- Delete description
- Link see more to agreement page

Update agreement card

---

next.config.js
package-lock.json
package.json
pages/_app.js

Utiliza configuración en ambiente staging y producción.
Closes #101

Adiciona configuración para Hotjar

---

pages/api/agreements/index.js
util/formatDate.js

Fix last events indicators

---

components/DownloadButton/styles.js
components/Home/index.js
components/Home/styles.js

Actualiza los enlaces en los botones y el texto en estos.
closes #109

Actualiza los enlaces en los botones de reportes

---

components/Home/index.js

Actualiza el enlace y el texto del botón para el más reciente reporte de mayo.
closes #111

Actualiza el enlace para el reporte en Mayo
